---
- hosts: all
  become: yes
  tasks:
    - name: Install jdk
      apt:
        name: openjdk-8-jre-headless
        state: present
    - name: add key
      apt_key: url=https://pkg.jenkins.io/debian/jenkins.io.key state=present

    - name: add repo
      apt_repository: repo='deb https://pkg.jenkins.io/debian binary/' state=present

    - name: install jenkins
      apt: name=jenkins update_cache=yes
